demomvc/Models/ErrorViewModel.cs
using System;

namespace demomvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

demomvc/Models/Ventas.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace demomvc.Models
{
    [Table("t_producto")]

    public class Ventas
    {
       [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
       [Column("id")]
       public int Id { get; set; }
       [Column("name")]
       public string Name{ get; set; }
       [Column("categoria")]
       public string Categoria{ get; set; }
       [Column("precio")]
       public decimal Precio{get; set;}
       [Column("descuento")]
       public string Descuento{get; set; }

    }
}

demomvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using demomvc.Models;

namespace demomvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

demomvc/Controllers/VentasController.cs
using Microsoft.AspNetCore.Mvc;
using demomvc.Models;
using demomvc.Data;
using System.Linq;

namespace demomvc.Controllers
{
    public class VentasController:Controller
    {
        private readonly ApplicationDbContext _context;
        
        public VentasController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            return View(_context.DataVentas.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Ventas objVentas)
        {
            _context.Add(objVentas);
            _context.SaveChanges();

            ViewData["Message"] = "Se registró con exito, gracias";
            return View();
        }
        public IActionResult Edit(int id)
        {
            Ventas objVentas = _context.DataVentas.Find(id);
            if(objVentas == null){
                return NotFound();
            }
            return View(objVentas);
        }

        [HttpPost]

        public ActionResult Edit(int id, [Bind("Id,Name,Categoria,Precio,Descuento")] Ventas objVentas)
        {
            _context.Update(objVentas);
            _context.SaveChanges();
            ViewData["Message"] = "Se actualizó correctamente";
             return View(objVentas);
        }

        public IActionResult Delete(int id)
        {
            Ventas objVentas = _context.DataVentas.Find(id);
            _context.DataVentas.Remove(objVentas);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

demomvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">☠ Página de Videojuegos ⚡ </h1>
    <p>En esta página podrá encontrar un formulario donde puede usted registrar la Venta de un productos.</p>
    <p>Leer <a href="#">Pagina WEB de JJRC</a>.</p>
</div>

demomvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - demomvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">🚂</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">|  Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="Index">|  Video Game</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Siguenos en todas nuestras redes sociales - <a asp-area="" asp-controller="Home" asp-action="Privacy">Click aquí</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

demomvc/Views/Ventas/Create.cshtml
@model demomvc.Models.Ventas

@{
    ViewData["Title"] = "Formulario VideoGame";
}

<div class="text-center">
    <h1>@ViewData["Title"]</h1>

    <h2>Producto</h2>



    <form asp-controller="Ventas" asp-action="Create">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control" placeholder="Escribir nombre del producto"/>

        <label asp-for="Categoria" class="control-label"></label>
        

        <select asp-for="Categoria" class="form-control">
            <option >Selecciona la categoria</option>
            <option value="Terror">Terror</option>
            <option value="Acción">Acción</option>
            <option value="Deportivo">Deportivo</option>
            <option value="Estrategia">Estrategia</option>
            <option value="Arcade">Arcade</option>
        </select>
       
        

        <label asp-for="Precio" class="control-label"></label>
        <input asp-for="Precio" class="form-control" placeholder=" Precio en soles" />

        <label asp-for="Descuento" class="control-label"></label>
        <input asp-for="Descuento" class="form-control" placeholder="%" />
        <br>
        <div class="form-group">
            <button type="submit" class="btn btn-info">Registrar</button> 
        </div>              
    </form>
    <h1>@ViewData["Message"]</h1>






    
</div>

demomvc/Views/Ventas/Edit.cshtml
@model demomvc.Models.Ventas

@{
    ViewData["Title"] = "Formulario VideoGame";
}

<div class="text-center">
    <h1>@ViewData["Title"]</h1>

    <h2>Producto</h2>



    <form asp-controller="Ventas" asp-action="Edit">
        <input type="hidden" asp-for="Id" />

        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control" placeholder="Escribir nombre del producto"/>

        <label asp-for="Categoria" class="control-label"></label>
        

        <select asp-for="Categoria" class="form-control">
            <option >Selecciona la categoria</option>
            <option value="Terror">Terror</option>
            <option value="Acción">Acción</option>
            <option value="Deportivo">Deportivo</option>
            <option value="Estrategia">Estrategia</option>
            <option value="Arcade">Arcade</option>
        </select>
       
        

        <label asp-for="Precio" class="control-label"></label>
        <input asp-for="Precio" class="form-control" placeholder=" Precio en soles" />

        <label asp-for="Descuento" class="control-label"></label>
        <input asp-for="Descuento" class="form-control" placeholder="%" />
        <br>
        <div class="form-group">
            <button type="submit" class="btn btn-info">Actualizar</button> 
        </div>              
    </form>
    <h1>@ViewData["Message"]</h1>






    
</div>

demomvc/Views/Ventas/Index.cshtml
@model IEnumerable<demomvc.Models.Ventas>
@{
    ViewData["Title"] = "Registro";
}
<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">Create</a>
</p>
<h2>List Games</h2>
<table class="table">
    <thead>
        <tr>
            <th>Opciones</th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descuento)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Borrar</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria)
            </td>
              <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descuento)
            </td>

        </tr>
}
    </tbody>
</table>